//WCC: wrapers for "pblas_level3.f".

#include <R.h>
#include <Rinternals.h>
#include "base_global.h"

SEXP R_PDTRAN(SEXP A, SEXP CLDIM, SEXP ICTXT, SEXP MYROW, SEXP MYCOL,
		SEXP DESCA, SEXP DESCC, SEXP M, SEXP N){
	SEXP C;
/*SEXP R_PDTRAN(SEXP M, SEXP N, SEXP A, SEXP DESCA, SEXP CLDIM, SEXP DESCC, SEXP ICTXT)*/
/*{*/
/*  SEXP C;*/
	PROTECT(C = allocMatrix(REALSXP, INTEGER(CLDIM)[0], INTEGER(CLDIM)[1]));

	F77_CALL(rpdtran)(REAL(A), REAL(C),
			INTEGER(ICTXT), INTEGER(MYROW), INTEGER(MYCOL),
			INTEGER(DESCA), INTEGER(DESCC),
			INTEGER(M), INTEGER(N));

/*	F77_CALL(pdtran)(INTEGER(M)[0], INTEGER(N)[0], 1.0, */
/*	    REAL(A), 1, 1, INTEGER(DESCA), 0.0, */
/*	    REAL(C), 1, 1, INTEGER(DESCC));*/

	UNPROTECT(1);
	return(C);
} /* End of R_PDTRAN(). */


SEXP R_PDGEMM(SEXP A, SEXP B, SEXP CLDIM, SEXP ICTXT, SEXP MYROW, SEXP MYCOL,
		SEXP DESCA, SEXP DESCB, SEXP DESCC,
		SEXP M, SEXP N, SEXP K){
	SEXP C;

	PROTECT(C = allocMatrix(REALSXP, INTEGER(CLDIM)[0], INTEGER(CLDIM)[1]));
	F77_CALL(rpdgemm)(REAL(A), REAL(B), REAL(C),
			INTEGER(ICTXT), INTEGER(MYROW), INTEGER(MYCOL),
			INTEGER(DESCA), INTEGER(DESCB), INTEGER(DESCC),
			INTEGER(M), INTEGER(N), INTEGER(K));
	UNPROTECT(1);

	return(C);
} /* End of R_PDGEMM(). */

